
-- description generated by Pat driver

--			date     : Fri Oct 20 18:07:07 2017
--			revision : v109

--			sequence : inv_4bits

-- input / output list :
in       a (3 downto 0) B;;
out      s (3 downto 0) B;;
in       vdd B;;
in       vss B;;

begin

-- Pattern description :

--                        a     s    v v  
--                                   d s  
--                                   d s  


-- Beware : unprocessed patterns

<          0 ps>        : 0000 ?1111 1 0 ;
<          1 ps>        : 0001 ?1110 1 0 ;
<          2 ps>        : 0010 ?1101 1 0 ;
<          3 ps>        : 0011 ?1100 1 0 ;
<          4 ps>        : 0100 ?1011 1 0 ;
<          5 ps>        : 0101 ?1010 1 0 ;
<          6 ps>        : 0110 ?1001 1 0 ;
<          7 ps>        : 0111 ?1000 1 0 ;
<          8 ps>        : 1000 ?0111 1 0 ;
<          9 ps>        : 1001 ?0110 1 0 ;
<         10 ps>        : 1010 ?0101 1 0 ;
<         11 ps>        : 1011 ?0100 1 0 ;
<         12 ps>        : 1100 ?0011 1 0 ;
<         13 ps>        : 1101 ?0010 1 0 ;
<         14 ps>        : 1110 ?0001 1 0 ;
<         15 ps>        : 1111 ?0000 1 0 ;

end;
